FROM python:3.11-slim

WORKDIR /app

# Build + runtime deps. `gosu` is needed by docker-entrypoint.sh so the
# container can chown bind mounts to the non-root user before dropping
# privileges (closes the bind-mount UID-mismatch issue from the audit).
# `curl` is intentionally NOT installed — the healthcheck below uses
# urllib instead, which keeps the image smaller and the attack surface
# tighter.
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    libgomp1 \
    libzbar0 \
    gosu \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies from the hash-pinned lock file generated by
# `uv pip compile requirements.txt -o requirements.lock --generate-hashes`.
# `--require-hashes` makes pip refuse to install anything not in the lock,
# which is the supply-chain protection from audit #14.
COPY requirements.lock .
RUN pip install --no-cache-dir --require-hashes -r requirements.lock

# Playwright: install Chromium + all system deps in one command.
# Keep browsers in a shared path so the non-root runtime user can launch
# Chromium; the default root cache is not visible after gosu drops privileges.
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
RUN playwright install --with-deps chromium \
    && chmod -R a+rX /ms-playwright

# Copy application code
COPY src/ src/
COPY templates/ templates/
COPY main.py .
COPY scripts/ scripts/
COPY tests/ tests/
COPY config.yaml .
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Create non-root user. The data/logs dirs are NOT created here — the
# entrypoint script creates them and chown's to the runtime UID after the
# bind mounts are visible (chown'ing a path before a bind mount is
# layered over it has no effect on Linux).
RUN useradd -m -u 1000 phishing

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    LOG_LEVEL=INFO \
    DASHBOARD_PORT=8000 \
    APP_UID=1000 \
    APP_GID=1000

# Healthcheck without curl — uses Python's urllib (already in stdlib).
# Smaller image, smaller attack surface, no extra package to track for
# CVEs. Audit #18.
HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \
    CMD python -c "import urllib.request,sys; \
        sys.exit(0 if urllib.request.urlopen('http://localhost:8000/api/health', timeout=5).status == 200 else 1)" \
        || exit 1

EXPOSE 8000

# Entrypoint runs as root briefly, fixes bind-mount ownership, then
# `gosu` drops to the phishing user before exec'ing CMD. Audit #19.
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["python", "main.py", "serve", "--host", "0.0.0.0", "--port", "8000"]
